repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length, "100"]
        language: python
        language_version: "3.11"
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language: python
        language_version: "3.11"
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile, black, --filter-files]
  - repo: https://github.com/pdm-project/pdm
    rev: 2.6.1 # a PDM release exposing the hook
    hooks:
      - id: pdm-lock-check
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports]
        additional_dependencies: [tokenize-rt==3.2.0]
        language: python
        language_version: "3.11"
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        language: python
        language_version: "3.11"